import {
  BiAlarmOff,
  BiHappyBeaming,
  BsFillShieldLockFill,
  BsFillStopwatchFill,
  BsFillTreeFill,
  BsFillUnlockFill,
  BsMusicNoteBeamed,
  BsPeace,
  FaChild,
  FaFistRaised,
  FaHandshake,
  FaPiggyBank,
  FaRegKissWinkHeart,
  FaTools,
  FiTarget,
  GiBreakingChain,
  GiChoice,
  GiClothes,
  GiCrossedSwords,
  GiFlyingFlag,
  GiGearHammer,
  GiGlowingHands,
  GiHeartInside,
  GiHeartKey,
  GiMedallist,
  GiMountainClimbing,
  GiMountainRoad,
  GiNightSleep,
  GiPalette,
  GiPillow,
  GiSplitArrows,
  GrLineChart,
  HiOutlineScale,
  HiPuzzle,
  MdAccessTime,
  MdConnectWithoutContact,
  MdFamilyRestroom,
  MdFitnessCenter,
  MdLeaderboard,
  MdMenuBook,
  MdOutlineThumbsUpDown,
  MdOutlineVerifiedUser,
  MdPsychology,
  MdSocialDistance,
  MdSportsSoccer,
  MdVolunteerActivism,
  RiEmotionSadLine,
  RiGovernmentLine,
  RiUserHeartFill,
  SiHandshake,
  GiLion,
  RiErrorWarningFill,
  FaGrinStars,
  GiTeacher,
  FaThumbsDown,
  GiSittingDog,
} from "react-icons/all";

const allTraits = [
  'Adventure',
  'Ambition',
  'Athleticism',
  'Boldness',
  'Caution',
  'Charisma',
  'Confrontation',
  'Craftsmanship',
  'Creativity',
  'Decisiveness',
  'Discipline',
  'Empathy',
  'Flexibility',
  'Frugality',
  'Independence',
  'Ingenuity',
  'Musical Skill',
    'Loyality',
  'Optimism',
  'Patience',
  'Peace',
  'Perseverance',
  'Personal Space',
  'Realism',
  'Physical Appearance',
  'Romance',
  'Self-Improvement',
  'Teachability',
  'Vulnerability',
];

export const traitIcons = {
  Artistry: <GiPalette />,
  "Musical Skill": <BsMusicNoteBeamed />,
  Leadership: <GiFlyingFlag />,
  Excellence: <MdLeaderboard />,
  "Self Control": <MdPsychology />,
  "Physical Appearance": <GiClothes />,
  Independence: <GiBreakingChain />,
  Flexibility: <GiSplitArrows />,
  "Personal Space": <MdSocialDistance />,
  Rest: <GiNightSleep />,
  Kindness: <RiUserHeartFill />,
  Recreation: <MdSportsSoccer />,
  Strength: <MdFitnessCenter />,
  Wisdom: <MdMenuBook />,
  Empathy: <MdConnectWithoutContact />,
  Trust: <SiHandshake />,
  Spontaneity: <BiAlarmOff />,
  Adventure: <GiMountainRoad />,
  Integrity: <MdOutlineVerifiedUser />,
  Generosity: <MdVolunteerActivism />,
  Patience: <MdAccessTime />,
  Perseverance: <GiMountainClimbing />,
  Mercy: <GiGlowingHands />,
  Romance: <GiHeartInside />,
  Athleticism: <GiMedallist />,
  "Constructive Criticism": <MdOutlineThumbsUpDown />,
  Productivity: <GiGearHammer />,
  Nature: <BsFillTreeFill />,
  Peace: <BsPeace />,
  Determination: <FaFistRaised />,
  Resourcefulness: <HiPuzzle />,
  Authority: <RiGovernmentLine />,
  Hope: <GiHeartKey />,
  Challenge: <GiCrossedSwords />,
  Decisiveness: <GiChoice />,
  Comfort: <GiPillow />,
  Joy: <BiHappyBeaming />,
  Fairness: <HiOutlineScale />,
  Affection: <FaRegKissWinkHeart />,
  Confidence: <BsFillShieldLockFill />,
  Respect: <FaHandshake />,
  Discipline: <BsFillStopwatchFill />,
  Frugality: <FaPiggyBank />,
  Suffering: <RiEmotionSadLine />,
  "Child-likeness": <FaChild />,
  Optimism: <GrLineChart />,
  Ambition: <FiTarget />,
  Craftsmanship: <FaTools />,
  Vulnerability: <BsFillUnlockFill />,
  Family: <MdFamilyRestroom />,
  Boldness: <GiLion/>,
  Caution: <RiErrorWarningFill/>,
  Confrontation: <GiCrossedSwords/>,
  Charisma: <FaGrinStars/>,
  Ingenuity: <HiPuzzle/>,
  Teachability: <GiTeacher/>,
  Pessimism: <FaThumbsDown/>,
  Loyal: <GiSittingDog/>

};
export default allTraits;
